### ISSUE TITLE
# Error: AttributeError: 'dict' object has no attribute 'hwFogAlpha' # 

### ISSUE THREAD

**Issue by mottosso** [mottosso/maya-capture#37]
Getting this, there's an attempt to use `delattr` on a dict.

```
Traceback (most recent call last):
  File "<maya console>", line 2, in <module>
  File "/net/homes/mottosso/pythonpath/capture.py", line 137, in capture
    _maintained_time()):
  File "/opt/autodesk/maya-2015.sp5/lib/python27.zip/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/opt/autodesk/maya-2015.sp5/lib/python27.zip/contextlib.py", line 112, in nested
    vars.append(enter())
  File "/opt/autodesk/maya-2015.sp5/lib/python27.zip/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/net/homes/mottosso/pythonpath/capture.py", line 566, in _applied_viewport2_options
    delattr(options, opt)
AttributeError: 'dict' object has no attribute 'hwFogAlpha' # 
# Error: AttributeError: 'dict' object has no attribute 'hwFogAlpha' # 
```

**Comment by BigRoy** [comment]
Ah interesting. The actual attribute error aside from that was because you were setting `hwFogAlpha` as `camera_options` but it is a `viewport2_options` attribute?

Funnily enough your commit made a fix in `_applied_camera_options`, but the same thing is also present in `_applied_viewport2_options` right?

**Comment by mottosso** [comment]
Oh, didn't notice that. Having a look.

How come these errors didn't appear in our tests? :(

**Comment by BigRoy** [comment]
> How come these errors didn't appear in our tests? :(

The specified features are available in `2016`. I think we should make a test that ensures wrong attributes are gracefully ignored and just logged as warnings. Or what do you think?

**Comment by mottosso** [comment]
> I think we should make a test that ensures wrong attributes are gracefully ignored and just logged as warnings.

Yeah, that's a good idea. At least until it can more gracefully detect the version, and not use things not supported in an app.
