### ISSUE TITLE
parse_active_view tries to parse non-modelPanel views

### ISSUE THREAD

**Issue by mottosso** [mottosso/maya-capture#41]
```python
preset = capture.parse_active_view()
# Error: modelEditor: Object 'scriptEditorPanel1' not found.
# Traceback (most recent call last):
#   File "<maya console>", line 3, in <module>
#   File "c:\pythonpath\capture.py", line 367, in parse_active_view
#     camera = cmds.modelEditor(panel, q=1, camera=1)
# RuntimeError: modelEditor: Object 'scriptEditorPanel1' not found. # 
```

We'll need to throw our own exception, and let the user know that he has to have a modelPanel active.

**Comment by mottosso** [comment]
Fixed in https://github.com/mottosso/maya-capture/commit/133ded46a7e6cc5e9e73c12cff90ca1f28b504fc
